import { requireSupabaseRuntimeClient } from "./supabaseRuntime";
import { normalizeVirgoYTRiskLevel, redactVirgoYTSensitiveText, virgoytPayloadDigest, type VirgoYTAgent, type VirgoYTProvider, type VirgoYTRiskLevel, type VirgoYTToolKind } from "./virgoytDb";

type Row = Record<string, any>;
const number = (value: number | string) => Number(value);
const date = (value?: string | null) => value ? new Date(value) : null;

async function openIdForUserId(userId: number) {
  const runtime = requireSupabaseRuntimeClient();
  const { data, error } = await runtime.from("jarvis_users").select("open_id").eq("id", userId).maybeSingle();
  if (error) throw new Error(`VirgoYT profile lookup failed: ${error.message}`);
  if (!data?.open_id) throw new Error("VirgoYT authenticated profile is unavailable");
  return data.open_id as string;
}
function fail(error: { message: string } | null, context: string) { if (error) throw new Error(`${context}: ${error.message}`); }
function project(row: Row, userId: number) { return { id: number(row.id), userId, name: row.name, slug: row.slug, description: row.description, status: row.status, defaultAgent: row.default_agent, createdAt: date(row.created_at)!, updatedAt: date(row.updated_at)! }; }
function run(row: Row, userId: number) { return { id: number(row.id), userId, projectId: number(row.project_id), conversationId: row.conversation_id === null ? null : number(row.conversation_id), agent: row.agent, provider: row.provider, modelId: row.model_id, status: row.status, requestSummary: row.request_summary, outputSummary: row.output_summary, failureReason: row.failure_reason, createdAt: date(row.created_at)!, startedAt: date(row.started_at), completedAt: date(row.completed_at), updatedAt: date(row.updated_at)! }; }
function step(row: Row, userId: number) { return { id: number(row.id), userId, projectId: number(row.project_id), runId: number(row.run_id), stepOrder: row.step_order, title: row.title, description: row.description, assignedAgent: row.assigned_agent, status: row.status, requiresApproval: row.requires_approval ? 1 : 0, createdAt: date(row.created_at)!, updatedAt: date(row.updated_at)! }; }
function proposal(row: Row, userId: number) { return { id: number(row.id), userId, projectId: number(row.project_id), runId: row.run_id === null ? null : number(row.run_id), toolKind: row.tool_kind, riskLevel: row.risk_level, status: row.status, title: row.title, payloadDigest: row.payload_digest, payloadJson: row.payload_json, expiresAt: date(row.expires_at), resolvedAt: date(row.resolved_at), executedAt: date(row.executed_at), createdAt: date(row.created_at)!, updatedAt: date(row.updated_at)! }; }
function audit(row: Row, userId: number) { return { id: number(row.id), userId, projectId: row.project_id === null ? null : number(row.project_id), runId: row.run_id === null ? null : number(row.run_id), proposalId: row.proposal_id === null ? null : number(row.proposal_id), eventKind: row.event_kind, detailsJson: row.details_json, createdAt: date(row.created_at)! }; }
function providerProfile(row: Row, userId: number) { return { id: number(row.id), userId, label: row.label, provider: row.provider, endpoint: row.endpoint, defaultModel: row.default_model, credentialRef: row.credential_ref, status: row.status, createdAt: date(row.created_at)!, updatedAt: date(row.updated_at)! }; }
function runner(row: Row, userId: number) { return { id: number(row.id), userId, projectId: row.project_id === null ? null : number(row.project_id), displayName: row.display_name, runnerType: row.runner_type, status: row.status, publicKeyFingerprint: row.public_key_fingerprint, lastSeenAt: date(row.last_seen_at), createdAt: date(row.created_at)!, updatedAt: date(row.updated_at)! }; }

export async function listVirgoYTProjects(userId: number) { const runtime = requireSupabaseRuntimeClient(); const openId = await openIdForUserId(userId); const { data, error } = await runtime.from("virgoyt_projects").select("*").eq("user_open_id", openId).order("updated_at", { ascending: false }); fail(error, "VirgoYT project listing failed"); return (data ?? []).map((row) => project(row, userId)); }
export async function createVirgoYTProject(input: { userId: number; name: string; slug: string; description?: string | null; defaultAgent: VirgoYTAgent }) { const runtime = requireSupabaseRuntimeClient(); const openId = await openIdForUserId(input.userId); const { data, error } = await runtime.from("virgoyt_projects").insert({ user_open_id: openId, name: input.name, slug: input.slug, description: input.description ?? null, default_agent: input.defaultAgent }).select("*").single(); fail(error, "VirgoYT project creation failed"); return project(data!, input.userId); }
export async function getVirgoYTProject(userId: number, projectId: number) { const runtime = requireSupabaseRuntimeClient(); const openId = await openIdForUserId(userId); const { data, error } = await runtime.from("virgoyt_projects").select("*").eq("id", projectId).eq("user_open_id", openId).maybeSingle(); fail(error, "VirgoYT project lookup failed"); return data ? project(data, userId) : undefined; }
export async function archiveVirgoYTProject(userId: number, projectId: number) { const runtime = requireSupabaseRuntimeClient(); const openId = await openIdForUserId(userId); const { data, error } = await runtime.from("virgoyt_projects").update({ status: "archived", updated_at: new Date().toISOString() }).eq("id", projectId).eq("user_open_id", openId).select("id"); fail(error, "VirgoYT project archive failed"); return data?.length ?? 0; }
export async function deleteEmptyVirgoYTProject(userId: number, projectId: number) {
  const runtime = requireSupabaseRuntimeClient(); const openId = await openIdForUserId(userId);
  const [runs, proposals, runners] = await Promise.all([
    runtime.from("virgoyt_runs").select("id").eq("user_open_id", openId).eq("project_id", projectId).limit(1),
    runtime.from("virgoyt_tool_proposals").select("id").eq("user_open_id", openId).eq("project_id", projectId).limit(1),
    runtime.from("virgoyt_runner_connections").select("id").eq("user_open_id", openId).eq("project_id", projectId).limit(1),
  ]);
  fail(runs.error, "VirgoYT project run check failed"); fail(proposals.error, "VirgoYT project proposal check failed"); fail(runners.error, "VirgoYT project runner check failed");
  if (runs.data?.length || proposals.data?.length || runners.data?.length) return 0;
  const audit = await runtime.from("virgoyt_audit_events").delete().eq("user_open_id", openId).eq("project_id", projectId);
  fail(audit.error, "VirgoYT project audit cleanup failed");
  const { data, error } = await runtime.from("virgoyt_projects").delete().eq("id", projectId).eq("user_open_id", openId).select("id");
  fail(error, "VirgoYT project deletion failed"); return data?.length ?? 0;
}

export async function listVirgoYTRuns(userId: number, projectId: number) { const runtime = requireSupabaseRuntimeClient(); const openId = await openIdForUserId(userId); const { data, error } = await runtime.from("virgoyt_runs").select("*").eq("user_open_id", openId).eq("project_id", projectId).order("created_at", { ascending: false }); fail(error, "VirgoYT run listing failed"); return (data ?? []).map((row) => run(row, userId)); }
export async function getVirgoYTRun(userId: number, projectId: number, runId: number) { const runtime = requireSupabaseRuntimeClient(); const openId = await openIdForUserId(userId); const { data, error } = await runtime.from("virgoyt_runs").select("*").eq("id", runId).eq("project_id", projectId).eq("user_open_id", openId).maybeSingle(); fail(error, "VirgoYT run lookup failed"); return data ? run(data, userId) : undefined; }
export async function createVirgoYTRun(input: { userId: number; projectId: number; conversationId?: number | null; agent: VirgoYTAgent; provider: VirgoYTProvider; modelId: string; requestSummary: string }) { const runtime = requireSupabaseRuntimeClient(); const openId = await openIdForUserId(input.userId); const { data, error } = await runtime.from("virgoyt_runs").insert({ user_open_id: openId, project_id: input.projectId, conversation_id: input.conversationId ?? null, agent: input.agent, provider: input.provider, model_id: input.modelId, request_summary: redactVirgoYTSensitiveText(input.requestSummary), status: "planning", started_at: new Date().toISOString() }).select("*").single(); fail(error, "VirgoYT run creation failed"); return run(data!, input.userId); }

export async function listVirgoYTPlanSteps(userId: number, projectId: number, runId: number) { const runtime = requireSupabaseRuntimeClient(); const openId = await openIdForUserId(userId); const { data, error } = await runtime.from("virgoyt_plan_steps").select("*").eq("user_open_id", openId).eq("project_id", projectId).eq("run_id", runId).order("step_order", { ascending: true }); fail(error, "VirgoYT plan listing failed"); return (data ?? []).map((row) => step(row, userId)); }
export async function createVirgoYTPlanStep(input: { userId: number; projectId: number; runId: number; stepOrder: number; title: string; description?: string | null; assignedAgent: VirgoYTAgent; requiresApproval: number }) { const runtime = requireSupabaseRuntimeClient(); const openId = await openIdForUserId(input.userId); const { data, error } = await runtime.from("virgoyt_plan_steps").insert({ user_open_id: openId, project_id: input.projectId, run_id: input.runId, step_order: input.stepOrder, title: input.title, description: input.description ? redactVirgoYTSensitiveText(input.description) : null, assigned_agent: input.assignedAgent, requires_approval: Boolean(input.requiresApproval) }).select("*").single(); fail(error, "VirgoYT plan step creation failed"); return step(data!, input.userId); }

export async function listVirgoYTToolProposals(userId: number, projectId: number) { const runtime = requireSupabaseRuntimeClient(); const openId = await openIdForUserId(userId); const { data, error } = await runtime.from("virgoyt_tool_proposals").select("*").eq("user_open_id", openId).eq("project_id", projectId).order("created_at", { ascending: false }); fail(error, "VirgoYT proposal listing failed"); return (data ?? []).map((row) => proposal(row, userId)); }
export async function getVirgoYTToolProposal(userId: number, projectId: number, proposalId: number) { const runtime = requireSupabaseRuntimeClient(); const openId = await openIdForUserId(userId); const { data, error } = await runtime.from("virgoyt_tool_proposals").select("*").eq("id", proposalId).eq("project_id", projectId).eq("user_open_id", openId).maybeSingle(); fail(error, "VirgoYT proposal lookup failed"); return data ? proposal(data, userId) : undefined; }
export async function createVirgoYTToolProposal(input: { userId: number; projectId: number; runId?: number | null; toolKind: VirgoYTToolKind; riskLevel: VirgoYTRiskLevel; title: string; details: string; payload?: unknown; expiresAt: Date }) { const runtime = requireSupabaseRuntimeClient(); const openId = await openIdForUserId(input.userId); const payload = input.payload ?? { details: redactVirgoYTSensitiveText(input.details) }; const { data, error } = await runtime.from("virgoyt_tool_proposals").insert({ user_open_id: openId, project_id: input.projectId, run_id: input.runId ?? null, tool_kind: input.toolKind, risk_level: normalizeVirgoYTRiskLevel(input.toolKind, input.riskLevel), title: redactVirgoYTSensitiveText(input.title), payload_digest: virgoytPayloadDigest(payload), payload_json: JSON.stringify(payload), expires_at: input.expiresAt.toISOString() }).select("*").single(); fail(error, "VirgoYT proposal creation failed"); return proposal(data!, input.userId); }
export async function resolveVirgoYTToolProposal(input: { userId: number; projectId: number; proposalId: number; decision: "approved" | "rejected"; approvalNonce: string; expiresAt: Date }) { const runtime = requireSupabaseRuntimeClient(); const openId = await openIdForUserId(input.userId); const { data, error } = await runtime.from("virgoyt_tool_proposals").update({ status: input.decision, resolved_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq("id", input.proposalId).eq("project_id", input.projectId).eq("user_open_id", openId).eq("status", "pending").select("*"); fail(error, "VirgoYT proposal resolution failed"); if (!data?.[0]) return undefined; const approval = await runtime.from("virgoyt_tool_approvals").insert({ user_open_id: openId, proposal_id: input.proposalId, decision: input.decision, approval_nonce: input.approvalNonce, expires_at: input.expiresAt.toISOString() }); fail(approval.error, "VirgoYT approval record creation failed"); return proposal(data[0], input.userId); }

export async function listVirgoYTAuditEvents(userId: number, projectId: number) { const runtime = requireSupabaseRuntimeClient(); const openId = await openIdForUserId(userId); const { data, error } = await runtime.from("virgoyt_audit_events").select("*").eq("user_open_id", openId).eq("project_id", projectId).order("created_at", { ascending: false }); fail(error, "VirgoYT audit listing failed"); return (data ?? []).map((row) => audit(row, userId)); }
export async function createVirgoYTAuditEvent(input: { userId: number; projectId?: number | null; runId?: number | null; proposalId?: number | null; eventKind: string; details: string }) { const runtime = requireSupabaseRuntimeClient(); const openId = await openIdForUserId(input.userId); const { error } = await runtime.from("virgoyt_audit_events").insert({ user_open_id: openId, project_id: input.projectId ?? null, run_id: input.runId ?? null, proposal_id: input.proposalId ?? null, event_kind: input.eventKind, details_json: JSON.stringify({ details: redactVirgoYTSensitiveText(input.details) }) }); fail(error, "VirgoYT audit creation failed"); }

export async function listVirgoYTProviderProfiles(userId: number) { const runtime = requireSupabaseRuntimeClient(); const openId = await openIdForUserId(userId); const { data, error } = await runtime.from("virgoyt_provider_profiles").select("*").eq("user_open_id", openId).order("updated_at", { ascending: false }); fail(error, "VirgoYT provider listing failed"); return (data ?? []).map((row) => providerProfile(row, userId)); }
export async function createVirgoYTProviderProfile(input: { userId: number; label: string; provider: VirgoYTProvider; endpoint?: string | null; defaultModel?: string | null }) { const runtime = requireSupabaseRuntimeClient(); const openId = await openIdForUserId(input.userId); const { data, error } = await runtime.from("virgoyt_provider_profiles").insert({ user_open_id: openId, label: input.label, provider: input.provider, endpoint: input.endpoint ?? null, default_model: input.defaultModel ?? null, credential_ref: null, status: "unconfigured" }).select("*").single(); fail(error, "VirgoYT provider creation failed"); return providerProfile(data!, input.userId); }

export async function listVirgoYTRunnerConnections(userId: number, projectId: number) { const runtime = requireSupabaseRuntimeClient(); const openId = await openIdForUserId(userId); const { data, error } = await runtime.from("virgoyt_runner_connections").select("*").eq("user_open_id", openId).eq("project_id", projectId).order("updated_at", { ascending: false }); fail(error, "VirgoYT runner listing failed"); return (data ?? []).map((row) => runner(row, userId)); }
export async function createVirgoYTRunnerConnection(input: { userId: number; projectId: number; displayName: string; runnerType: "local_cli" | "remote_isolated"; pairingFingerprint?: string | null }) { const runtime = requireSupabaseRuntimeClient(); const openId = await openIdForUserId(input.userId); const { data, error } = await runtime.from("virgoyt_runner_connections").insert({ user_open_id: openId, project_id: input.projectId, display_name: input.displayName, runner_type: input.runnerType, public_key_fingerprint: input.pairingFingerprint ?? null, status: "pending" }).select("*").single(); fail(error, "VirgoYT runner creation failed"); return runner(data!, input.userId); }
export async function pairVirgoYTRunner(runnerId: number, pairingFingerprint: string) { const runtime = requireSupabaseRuntimeClient(); const { data, error } = await runtime.from("virgoyt_runner_connections").update({ status: "paired", last_seen_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq("id", runnerId).eq("public_key_fingerprint", pairingFingerprint).eq("status", "pending").select("id"); fail(error, "VirgoYT runner pairing failed"); return data?.length ?? 0; }
export async function getVirgoYTRunnerByPairingFingerprint(runnerId: number, pairingFingerprint: string) { const runtime = requireSupabaseRuntimeClient(); const { data, error } = await runtime.from("virgoyt_runner_connections").select("*").eq("id", runnerId).eq("public_key_fingerprint", pairingFingerprint).maybeSingle(); fail(error, "VirgoYT runner lookup failed"); if (!data) return undefined; const { data: user, error: userError } = await runtime.from("jarvis_users").select("id").eq("open_id", data.user_open_id).maybeSingle(); fail(userError, "VirgoYT runner owner lookup failed"); return user?.id ? runner(data, Number(user.id)) : undefined; }
export async function touchVirgoYTRunner(runnerId: number, pairingFingerprint: string) { const runtime = requireSupabaseRuntimeClient(); const { data, error } = await runtime.from("virgoyt_runner_connections").update({ status: "active", last_seen_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq("id", runnerId).eq("public_key_fingerprint", pairingFingerprint).in("status", ["paired", "active"]).select("id"); fail(error, "VirgoYT runner heartbeat failed"); return data?.length ?? 0; }
export async function claimVirgoYTCompileProposal(input: { runnerId: number; pairingFingerprint: string }) { const runnerRecord = await getVirgoYTRunnerByPairingFingerprint(input.runnerId, input.pairingFingerprint); if (!runnerRecord?.projectId || !runnerRecord.userId || !["paired", "active"].includes(runnerRecord.status)) return undefined; const runtime = requireSupabaseRuntimeClient(); const openId = await openIdForUserId(runnerRecord.userId); const { data, error } = await runtime.from("virgoyt_tool_proposals").select("*").eq("user_open_id", openId).eq("project_id", runnerRecord.projectId).eq("tool_kind", "terminal_command").eq("status", "approved").order("created_at", { ascending: true }).limit(1); fail(error, "VirgoYT compile claim lookup failed"); const row = data?.[0]; if (!row) return undefined; const claim = await runtime.from("virgoyt_tool_proposals").update({ status: "claimed", updated_at: new Date().toISOString() }).eq("id", row.id).eq("status", "approved").select("*"); fail(claim.error, "VirgoYT compile claim failed"); if (!claim.data?.[0]) return undefined; await touchVirgoYTRunner(input.runnerId, input.pairingFingerprint); return proposal(claim.data[0], runnerRecord.userId); }
export async function completeVirgoYTCompileProposal(input: { runnerId: number; pairingFingerprint: string; proposalId: number; success: boolean; details: string }) { const runnerRecord = await getVirgoYTRunnerByPairingFingerprint(input.runnerId, input.pairingFingerprint); if (!runnerRecord?.projectId || !runnerRecord.userId) return undefined; const runtime = requireSupabaseRuntimeClient(); const openId = await openIdForUserId(runnerRecord.userId); const { data, error } = await runtime.from("virgoyt_tool_proposals").update({ status: input.success ? "executed" : "failed", executed_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq("id", input.proposalId).eq("user_open_id", openId).eq("project_id", runnerRecord.projectId).eq("status", "claimed").select("*"); fail(error, "VirgoYT compile completion failed"); if (!data?.[0]) return undefined; await createVirgoYTAuditEvent({ userId: runnerRecord.userId, projectId: runnerRecord.projectId, proposalId: input.proposalId, eventKind: input.success ? "compile_completed" : "compile_failed", details: input.details }); await touchVirgoYTRunner(input.runnerId, input.pairingFingerprint); return proposal(data[0], runnerRecord.userId); }
