import { Archive, Menu, MessageSquareText, Plus, Search, Star, X } from "lucide-react";
import React from "react";
import { cn } from "@/lib/utils";
import { JarvisModeNav, type JarvisWorkspaceMode } from "./JarvisModeNav";

type Conversation = { id: number; title: string; starredAt?: Date | string | number | null; updatedAt?: Date | string | number | null };

export function JarvisWorkspaceRail({ activeMode, conversations, mobileOpen, onCloseMobile, onModeChange, onNewChat, onSelectConversation, onToggleStar, pendingApprovals, userName }: { activeMode: JarvisWorkspaceMode; conversations: Conversation[]; mobileOpen: boolean; onCloseMobile: () => void; onModeChange: (mode: JarvisWorkspaceMode) => void; onNewChat: () => void; onSelectConversation: (id: number) => void; onToggleStar: (id: number, starred: boolean) => void; pendingApprovals: number; userName?: string | null }) {
  const [query, setQuery] = React.useState("");
  const chooseMode = (mode: JarvisWorkspaceMode) => { onModeChange(mode); onCloseMobile(); };
  const matches = conversations.filter((conversation) => conversation.title.toLowerCase().includes(query.trim().toLowerCase()));
  const starred = matches.filter((conversation) => Boolean(conversation.starredAt));
  const recent = matches.filter((conversation) => !conversation.starredAt);
  const chatRow = (conversation: Conversation) => <div key={conversation.id} className="group flex min-w-0 items-center gap-1 rounded-md pr-1 transition hover:bg-white/[0.05]"><button onClick={() => { onSelectConversation(conversation.id); chooseMode("chats"); }} className="flex min-w-0 flex-1 items-center gap-2 rounded-md px-2.5 py-2 text-left text-xs text-slate-400 transition hover:text-slate-100"><MessageSquareText className="size-3.5 shrink-0 text-slate-600" /><span className="truncate">{conversation.title}</span></button><button onClick={() => onToggleStar(conversation.id, !conversation.starredAt)} aria-label={`${conversation.starredAt ? "Remove" : "Add"} ${conversation.title} ${conversation.starredAt ? "from" : "to"} starred chats`} className={cn("flex size-7 shrink-0 items-center justify-center rounded-md transition", conversation.starredAt ? "text-amber-200" : "text-slate-700 opacity-100 hover:text-slate-300 md:opacity-0 md:group-hover:opacity-100")}><Star className={cn("size-3.5", conversation.starredAt && "fill-current")} /></button></div>;
  const railContent = (
    <div className="flex h-full min-h-0 flex-col">
      <div className="flex items-center justify-between border-b border-white/8 px-4 py-4"><div className="flex items-center gap-2.5"><div className="flex size-8 items-center justify-center rounded-lg border border-cyan-200/30 bg-cyan-300/10 font-mono text-xs font-bold text-cyan-100">J</div><div><p className="font-mono text-xs font-bold tracking-[0.24em] text-cyan-50">JARVIS</p><p className="mt-0.5 text-[10px] text-slate-500">PRIVATE WORKSPACE</p></div></div><button onClick={onCloseMobile} aria-label="Close workspace menu" className="flex size-8 items-center justify-center rounded-md text-slate-400 hover:bg-white/5 md:hidden"><X className="size-4" /></button></div>
      <div className="p-3"><button onClick={onNewChat} className="flex w-full items-center justify-center gap-2 rounded-lg bg-cyan-200 px-3 py-2.5 text-xs font-semibold text-slate-950 transition hover:bg-cyan-100 active:scale-[0.97]"><Plus className="size-3.5" /> New chat</button></div>
      <div className="px-2"><JarvisModeNav activeMode={activeMode} onModeChange={chooseMode} pendingApprovals={pendingApprovals} variant="rail" /></div>
      <div className="mt-4 min-h-0 flex-1 overflow-y-auto border-t border-white/8 px-3 pt-4"><div className="flex items-center justify-between px-1"><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500">Private chats</p><Archive className="size-3.5 text-slate-600" /></div><label className="mt-3 flex items-center gap-2 rounded-md border border-white/8 bg-black/20 px-2.5 py-2 text-slate-500 focus-within:border-cyan-300/30"><Search className="size-3.5" /><input aria-label="Search private chats" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search chats" className="min-w-0 flex-1 bg-transparent text-xs text-slate-200 outline-none placeholder:text-slate-600" /></label>{starred.length > 0 && <div className="mt-4"><p className="px-1 text-[10px] font-semibold uppercase tracking-[0.18em] text-amber-200/70">Starred</p><div className="mt-2 space-y-1">{starred.map(chatRow)}</div></div>}<div className="mt-4"><p className="px-1 text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500">{query ? "Matches" : "Recent"}</p><div className="mt-2 space-y-1">{recent.map(chatRow)}{conversations.length === 0 && <p className="px-2 py-3 text-xs leading-5 text-slate-600">New conversations will appear here privately.</p>}{conversations.length > 0 && matches.length === 0 && <p className="px-2 py-3 text-xs leading-5 text-slate-600">No private chat matches that search.</p>}</div></div></div>
      <div className="m-3 mt-4 rounded-lg border border-white/8 bg-white/[0.025] p-3"><p className="truncate text-xs font-medium text-slate-300">{userName ?? "Your private workspace"}</p><p className="mt-1 text-[10px] leading-4 text-slate-600">Each signed-in user sees only their own chats and records.</p></div>
    </div>
  );
  return <><aside className="jarvis-workspace-rail sticky top-5 hidden h-[calc(100vh-40px)] overflow-hidden rounded-xl border border-white/10 bg-slate-950/75 shadow-2xl backdrop-blur-xl md:block">{railContent}</aside><div className={cn("fixed inset-0 z-[70] md:hidden", mobileOpen ? "pointer-events-auto" : "pointer-events-none")} aria-hidden={!mobileOpen}><button onClick={onCloseMobile} aria-label="Close workspace menu overlay" className={cn("absolute inset-0 bg-black/65 transition-opacity", mobileOpen ? "opacity-100" : "opacity-0")} /><aside className={cn("absolute inset-y-0 left-0 w-[min(84vw,330px)] border-r border-white/10 bg-slate-950 shadow-2xl transition-transform duration-200", mobileOpen ? "translate-x-0" : "-translate-x-full")}>{railContent}</aside></div></>;
}

export function JarvisMobileWorkspaceTrigger({ onOpen }: { onOpen: () => void }) {
  return <button onClick={onOpen} aria-label="Open workspace menu" className="flex size-9 items-center justify-center rounded-lg border border-white/10 bg-white/[0.035] text-slate-200 transition hover:bg-white/[0.08] active:scale-[0.97] md:hidden"><Menu className="size-4" /></button>;
}
