import { BrainCircuit, Filter, LockKeyhole, Plus, Search, ShieldCheck, Tags, Trash2 } from "lucide-react";
import React, { useMemo, useState } from "react";
import { HudPanel } from "@/components/HudPanel";
import { cn } from "@/lib/utils";
import { JarvisGlyph } from "./JarvisGlyph";

export const jarvisMemoryCategories = ["note", "preference", "project", "personal", "fact"] as const;
export type JarvisMemoryCategory = (typeof jarvisMemoryCategories)[number];
export type JarvisMemoryRecord = { id: number; content: string; category: JarvisMemoryCategory; createdAt?: Date | string | number | null; source?: string | null };

const categoryTone: Record<JarvisMemoryCategory, string> = {
  note: "border-slate-400/20 bg-slate-300/[0.06] text-slate-300",
  preference: "border-cyan-300/25 bg-cyan-300/[0.07] text-cyan-100",
  project: "border-fuchsia-300/25 bg-fuchsia-300/[0.07] text-fuchsia-100",
  personal: "border-amber-300/25 bg-amber-300/[0.07] text-amber-100",
  fact: "border-emerald-300/25 bg-emerald-300/[0.07] text-emerald-100",
};

function label(category: JarvisMemoryCategory) { return category === "note" ? "Notes" : `${category[0].toUpperCase()}${category.slice(1)}s`; }
function safeDate(value: JarvisMemoryRecord["createdAt"]) { return value ? new Date(value).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }) : "Private record"; }

export function JarvisMemoryDashboard({ memories, durableMemoryEnabled, onDurableMemoryChange, onCreate, onDelete, onUpdateCategory, isSaving = false }: {
  memories: JarvisMemoryRecord[];
  durableMemoryEnabled: boolean;
  onDurableMemoryChange: (enabled: boolean) => void;
  onCreate: (content: string, category: JarvisMemoryCategory) => Promise<void> | void;
  onDelete: (id: number) => Promise<void> | void;
  onUpdateCategory: (memory: JarvisMemoryRecord, category: JarvisMemoryCategory) => Promise<void> | void;
  isSaving?: boolean;
}) {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState<JarvisMemoryCategory | "all">("all");
  const [draft, setDraft] = useState("");
  const [draftCategory, setDraftCategory] = useState<JarvisMemoryCategory>("note");
  const visible = useMemo(() => memories.filter((memory) => (category === "all" || memory.category === category) && memory.content.toLowerCase().includes(query.trim().toLowerCase())), [category, memories, query]);
  const distribution = useMemo(() => jarvisMemoryCategories.map((item) => ({ item, count: memories.filter((memory) => memory.category === item).length })), [memories]);
  const save = async () => { const content = draft.trim(); if (!content) return; await onCreate(content, draftCategory); setDraft(""); setDraftCategory("note"); };

  return <section aria-label="Memory dashboard" className="w-full space-y-3">
    <HudPanel className="relative overflow-hidden p-5 sm:p-6">
      <div className="jarvis-memory-dashboard__mesh" aria-hidden="true" />
      <div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-2xl"><div className="flex items-center gap-3"><JarvisGlyph size={42} status={durableMemoryEnabled ? "active" : "guarded"} /><div><p className="hud-label">JARVIS MEMORY VAULT</p><p className="mt-1 text-[10px] tracking-[0.16em] text-slate-500">PRIVATE CONTEXT / USER-SCOPED</p></div></div><h1 className="mt-5 text-2xl font-semibold tracking-tight text-white sm:text-3xl">Keep what matters. <span className="text-cyan-100">Control the rest.</span></h1><p className="mt-3 max-w-xl text-sm leading-6 text-slate-400">Review every saved fact, preference, and project note in one private place. Jarvis never shares these records across accounts.</p></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-3"><div className="rounded-sm border border-cyan-300/20 bg-cyan-300/[0.06] px-3 py-2.5"><p className="hud-label text-[8px]">SAVED</p><p className="mt-1 font-mono text-xl text-cyan-50">{memories.length}</p></div><div className="rounded-sm border border-fuchsia-300/20 bg-fuchsia-300/[0.06] px-3 py-2.5"><p className="hud-label text-[8px]">CATEGORIES</p><p className="mt-1 font-mono text-xl text-fuchsia-100">{distribution.filter((item) => item.count > 0).length}</p></div><div className="col-span-2 rounded-sm border border-emerald-300/20 bg-emerald-300/[0.06] px-3 py-2.5 sm:col-span-1"><p className="hud-label text-[8px]">AUTO-CAPTURE</p><p className="mt-1 font-mono text-xs text-emerald-100">{durableMemoryEnabled ? "ACTIVE" : "MANUAL"}</p></div></div></div>
    </HudPanel>

    <div className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_330px]">
      <HudPanel className="min-w-0 overflow-hidden">
        <div className="border-b border-white/[0.08] p-4 sm:p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><p className="hud-label">SAVED CONTEXT</p><p className="mt-1 text-xs text-slate-500">Search and classify your private records.</p></div><div className="flex flex-wrap gap-2"><label className="flex min-w-[190px] flex-1 items-center gap-2 rounded-sm border border-white/10 bg-black/20 px-3 py-2 text-slate-500 focus-within:border-cyan-300/35 lg:flex-none"><Search className="size-3.5" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search memories" className="min-w-0 flex-1 bg-transparent text-xs text-slate-100 outline-none placeholder:text-slate-600" /></label><label className="flex items-center gap-2 rounded-sm border border-white/10 bg-black/20 px-3 py-2 text-slate-400"><Filter className="size-3.5" /><select aria-label="Filter memories by category" value={category} onChange={(event) => setCategory(event.target.value as JarvisMemoryCategory | "all")} className="bg-transparent text-xs outline-none"><option className="bg-slate-950" value="all">All types</option>{jarvisMemoryCategories.map((item) => <option className="bg-slate-950" key={item} value={item}>{label(item)}</option>)}</select></label></div></div><div className="mt-4 flex flex-wrap gap-2">{distribution.map(({ item, count }) => <button key={item} type="button" onClick={() => setCategory(category === item ? "all" : item)} className={cn("rounded-full border px-2.5 py-1 text-[10px] font-medium transition", category === item ? categoryTone[item] : "border-white/[0.08] bg-white/[0.02] text-slate-500 hover:border-white/20 hover:text-slate-300")}>{label(item)} <span className="ml-1 font-mono opacity-70">{count}</span></button>)}</div></div>
        <div className="max-h-[min(58vh,650px)] space-y-2 overflow-y-auto p-3 sm:p-4">{visible.map((memory) => <article key={memory.id} className="group rounded-lg border border-white/[0.08] bg-black/15 p-3.5 transition hover:border-cyan-300/20 hover:bg-cyan-300/[0.025]"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={cn("rounded-full border px-2 py-0.5 text-[9px] font-semibold uppercase tracking-[0.13em]", categoryTone[memory.category])}>{memory.category}</span><span className="text-[10px] text-slate-600">{safeDate(memory.createdAt)}</span>{memory.source === "auto" && <span className="text-[9px] uppercase tracking-[0.14em] text-cyan-200/75">Jarvis-captured</span>}</div><p className="mt-2 text-sm leading-6 text-slate-300">{memory.content}</p></div><button type="button" aria-label={`Delete memory ${memory.id}`} title="Delete memory" onClick={() => void onDelete(memory.id)} className="flex size-8 shrink-0 items-center justify-center rounded-sm text-slate-600 transition hover:bg-rose-400/10 hover:text-rose-200"><Trash2 className="size-3.5" /></button></div><div className="mt-3 flex items-center gap-2 border-t border-white/[0.06] pt-2.5"><Tags className="size-3 text-slate-600" /><select aria-label={`Category for memory ${memory.id}`} value={memory.category} onChange={(event) => void onUpdateCategory(memory, event.target.value as JarvisMemoryCategory)} className="bg-transparent text-[10px] text-slate-500 outline-none hover:text-cyan-100">{jarvisMemoryCategories.map((item) => <option className="bg-slate-950" value={item} key={item}>{label(item)}</option>)}</select></div></article>)}{visible.length === 0 && <div className="flex min-h-48 flex-col items-center justify-center rounded-lg border border-dashed border-white/10 bg-black/10 px-5 text-center"><BrainCircuit className="size-7 text-slate-700" /><p className="mt-3 text-sm text-slate-400">{memories.length ? "No memories match this filter." : "No private memories are saved yet."}</p><p className="mt-1 max-w-sm text-xs leading-5 text-slate-600">Add a fact or preference below. You remain in control of what Jarvis keeps.</p></div>}</div>
      </HudPanel>

      <div className="space-y-3"><HudPanel className="p-5"><div className="flex items-center gap-2"><Plus className="size-4 text-cyan-200" /><p className="hud-label">SAVE A MEMORY</p></div><textarea value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="For example: I prefer concise project updates." className="mt-4 min-h-28 w-full resize-none rounded-sm border border-white/10 bg-black/30 p-3 text-sm text-slate-200 outline-none placeholder:text-slate-600 focus:border-cyan-300/35" /><label className="mt-3 block"><span className="sr-only">New memory category</span><select value={draftCategory} onChange={(event) => setDraftCategory(event.target.value as JarvisMemoryCategory)} className="w-full rounded-sm border border-white/10 bg-black/30 px-3 py-2.5 text-xs text-slate-300 outline-none focus:border-cyan-300/35">{jarvisMemoryCategories.map((item) => <option key={item} value={item}>{label(item)}</option>)}</select></label><button disabled={!draft.trim() || isSaving} onClick={() => void save()} className="mt-3 flex w-full items-center justify-center gap-2 rounded-sm border border-cyan-300/30 bg-cyan-300/10 px-3 py-2.5 text-xs font-semibold text-cyan-50 transition hover:bg-cyan-300/20 disabled:cursor-not-allowed disabled:opacity-40"><Plus className="size-3.5" />SAVE PRIVATELY</button></HudPanel><HudPanel className="p-5"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-emerald-200" /><div><p className="hud-label">DURABLE MEMORY</p><p className="mt-2 text-xs leading-5 text-slate-500">When enabled, Jarvis may preserve clear, useful non-sensitive facts from your completed chats. You can remove any record here.</p></div></div><button type="button" role="switch" aria-checked={durableMemoryEnabled} onClick={() => onDurableMemoryChange(!durableMemoryEnabled)} className={cn("mt-4 flex w-full items-center justify-between rounded-sm border px-3 py-2.5 text-left transition", durableMemoryEnabled ? "border-emerald-300/30 bg-emerald-300/[0.08] text-emerald-100" : "border-white/10 bg-white/[0.02] text-slate-400")}><span className="text-xs font-medium">{durableMemoryEnabled ? "Automatic capture enabled" : "Manual memory only"}</span><span className={cn("relative h-5 w-9 rounded-full border", durableMemoryEnabled ? "border-emerald-200/40 bg-emerald-300/20" : "border-slate-600 bg-black/30")}><span className={cn("absolute top-0.5 size-3.5 rounded-full transition-transform", durableMemoryEnabled ? "translate-x-[17px] bg-emerald-100" : "translate-x-0.5 bg-slate-500")} /></span></button><div className="mt-4 flex gap-2 rounded-sm border border-white/[0.07] bg-black/15 p-2.5"><LockKeyhole className="mt-0.5 size-3.5 shrink-0 text-slate-600" /><p className="text-[10px] leading-4 text-slate-600">These records are private to this signed-in account. No provider key, browser session, or credential is stored as a memory.</p></div></HudPanel></div>
    </div>
  </section>;
}
